// components/CleverButton.vue
<template>
  <clever-link
    :to="to"
    :class="[
      'inline-flex justify-center text-white items-center font-inherit rounded-md py-4 px-8 no-underline transition-opacity duration-300 hover:opacity-90 focus:opacity-90 active:opacity-90 md:text-lg',
      isPrimary && 'bg-vsp-500',
      isSecondary && 'bg-gray-400',
    ]"
  >
    <slot />
  </clever-link>
</template>

<script>
export default {
  name: 'CleverButton',

  props: {
    to: {
      type: String,
      required: true,
    },
    variant: {
      type: String,
      default: 'primary',
    },
  },
  computed: {
    isPrimary() {
      return this.variant === 'primary'
    },
    isSecondary() {
      return this.variant === 'secondary'
    },
  },
}
</script>

// app/components/CleverButton.tsx
import CleverLink from "./CleverLink";
import type { ReactNode } from "react";

type buttonVariant = "primary" | "secondary";

type CleverButtonProps = {
  variant?: buttonVariant;
  children: ReactNode;
  to: string;
};

export default function CleverButton({
  children,
  variant = "primary",
  to,
}: CleverButtonProps) {
  const variantClass =
    variant === "primary"
      ? "bg-vsp-500"
      : variant === "secondary"
      ? "bg-gray-400"
      : "";
  return (
    <CleverLink
      to={to}
      className={`font-inherit inline-flex items-center justify-center rounded-md py-4 px-8 text-white no-underline transition-opacity duration-300 hover:opacity-90 focus:opacity-90 active:opacity-90 md:text-lg ${variantClass}`}
    >
      {children}
    </CleverLink>
  );
}
