// components/FadeIn.vue
<template>
  <div
    v-observe-visibility="visibilityChanged"
    :class="[
      'opacity-0 translate-y-10 scale-95 transition-all duration-300',
      isVisible && 'opacity-100 transform-none',
    ]"
  >
    <slot />
  </div>
</template>

<script>
export default {
  name: 'FadeIn',

  data() {
    return {
      isVisible: false,
    }
  },

  methods: {
    visibilityChanged(isVisible, entry) {
      if (!this.isVisible && isVisible) {
        this.isVisible = true
      }
    },
  },
}
</script>

// app/components/FadeIn.tsx
import { useRef } from "react";

import { useIntersectionObserver } from "usehooks-ts";

export default function FadeIn({ children }: { children: React.ReactNode }) {
  const ref = useRef<HTMLDivElement | null>(null);
  const entry = useIntersectionObserver(ref, {});
  const isVisible = !!entry?.isIntersecting;

  return (
    <div
      ref={ref}
      className={`translate-y-10 scale-95 opacity-0 transition-all duration-300 ${
        isVisible && "transform-none opacity-100"
      }`}
    >
      {children}
    </div>
  );
}
