// components/layout/NavItem.vue
<template>
  <li class="w-full block lg:w-auto lg:mr-1" @click="$emit('click')">
    <nuxt-link
      class="block p-4 no-underline lg:inline-block lg:py-1 lg:px-2 lg:rounded-md"
      active-class="bg-gray-100 lg:bg-white border-l-4 border-l-vsp-500 lg:border-none"
      :to="to"
    >
      <slot />
    </nuxt-link>
  </li>
</template>

<script>
export default {
  name: 'NavItem',
  props: {
    to: {
      type: String,
      required: true,
    },
  },
}
</script>

// app/components/layout/NavItem.tsx
import { NavLink } from "remix";
import type { ReactNode } from "react";

type NavItemProps = {
  to: string;
  children: ReactNode;
};

export default function NavItem({ to, children }: NavItemProps) {
  return (
    <li className="block w-full lg:mr-1 lg:w-auto">
      <NavLink
        className={({ isActive }) =>
          `block p-4 no-underline lg:inline-block lg:rounded-md lg:py-1 lg:px-2 ${
            isActive &&
            "border-l-4 border-l-vsp-500 bg-gray-100 lg:border-none lg:bg-white"
          }`
        }
        to={to}
      >
        {children}
      </NavLink>
    </li>
  );
}
