// components/GenericContent.vue
<template>
  <section class="mx-auto pt-24 px-4 pb-12 min-h-[50vh] w-screen max-w-3xl">
    <ContentfulRichText :content="block.fields.content" />
  </section>
</template>
<script>
export default {
  name: 'GenericContent',
  props: {
    block: {
      type: Object,
      required: true,
    },
  },
}
</script>

// app/components/ContentBlocks/GenericContent.tsx
import type { Entry } from "contentful";
import type { TypeGenericContentSkeleton } from "../../../types/contentful";
import ContentfulRichText from "../ContentfulRichText";

type GenericContentProps = Entry<
  TypeGenericContentSkeleton,
  "WITHOUT_UNRESOLVABLE_LINKS"
>["fields"];

export default function GenericContent({ content }: GenericContentProps) {
  return (
    <section className="mx-auto min-h-[50vh] w-screen max-w-3xl px-4 pt-24 pb-12">
      {content && <ContentfulRichText content={content} />}
    </section>
  );
}
