// pages/netzwerk-partner-medien.vue
<template>
  <div class="pt-24">
    <section
      v-if="network.length > 0"
      class="max-w-7xl mx-auto py-12 px-4 md:px-12"
    >
      <h2>{{ $t('network') }}</h2>
      <div :class="[$style.tiles, 'grid grid-rows-auto gap-x-4 gap-y-8']">
        <SupporterTile
          v-for="entry in network"
          :key="entry.fields.url"
          :url="entry.fields.url"
          :image="entry.fields.image.fields.file.url"
        />
      </div>
    </section>
    <section v-if="supporter.length > 0" :class="$style.tileSection">
      <h2>{{ $t('partner') }}</h2>
      <div :class="[$style.tiles, 'grid grid-rows-auto gap-x-4 gap-y-8']">
        <SupporterTile
          v-for="entry in supporter"
          :key="entry.fields.url"
          :url="entry.fields.url"
          :image="entry.fields.image.fields.file.url"
        />
      </div>
    </section>
    <ContentBlocks :blocks="content" />
    <section v-if="media.length > 0" :class="$style.tileSection">
      <h2>{{ $t('media') }}</h2>
      <div :class="[$style.tiles, 'grid grid-rows-auto gap-x-4 gap-y-8']">
        <SupporterTile
          v-for="medium in media"
          :key="medium.fields.url"
          :url="medium.fields.url"
          :title="medium.fields.title"
          :image="medium.fields.image.fields.file.url"
        />
      </div>
    </section>
  </div>
</template>

<script>
import pageIds from '~/utils/pageIds'
import getSiteMeta from '~/utils/getSiteMeta'

export default {
  name: 'SupportMedia',
  transition: 'page',

  meta: {
    inMainNav: true,
    title: 'Netzwerk, Partner + Medien',
  },

  nuxtI18n: {
    paths: {
      de: '/netzwerk-partner-medien',
      en: '/network-partner-media',
    },
  },

  async asyncData({ app, $contentful }) {
    const { fields } = await $contentful.getEntry(pageIds.NETWORK, {
      locale: app.i18n.locale,
    })
    const media = await $contentful.getEntries({
      content_type: 'media',
      order: 'fields.title',
    })
    const supporter = await $contentful.getEntries({
      content_type: 'supporter',
      order: 'fields.title',
    })
    const network = await $contentful.getEntries({
      content_type: 'network',
      order: 'fields.title',
    })
    return {
      title: fields.title,
      content: fields.content,
      seo: fields.seo?.fields,
      media: media.items,
      supporter: supporter.items,
      network: network.items,
    }
  },
  head() {
    const title = this.seo ? this.seo.title : this.title
    const metaInput = {
      title,
      description: this.seo?.description,
      url: this.$route.path,
      image: this.seo?.image?.fields.file?.url,
    }

    const meta = getSiteMeta(metaInput)

    return {
      title,
      meta,
    }
  },
}
</script>

<style module>
.tiles {
  grid-template-columns: repeat(auto-fit, minmax(270px, 1fr));
}
</style>

// app/routes/de/netzwerk-partner-medien.tsx
import { useLoaderData } from "remix";
import type { LoaderFunction, MetaFunction } from "remix";
import { useTranslation } from "react-i18next";
import {
  getMainNav,
  getPageById,
  getNetwork,
  getSupporters,
  getMedia,
} from "~/utils/contentful";
import ContentBlocks from "~/components/ContentBlocks";
import pageIds from "~/utils/pageIds";
import BasicLayout from "~/components/layout/BasicLayout";
import SupporterTile from "~/components/SupporterTile";
import { getSeoMeta } from "~/seo";

export const meta: MetaFunction = ({ data }) => {
  const { title, seo } = data?.page?.fields;

  let seoMeta = getSeoMeta({
    title: seo?.fields?.title || title,
    description: seo?.fields?.description || null,
  });
  return {
    ...seoMeta,
  };
};

export const loader: LoaderFunction = async () => {
  const locale = "de";

  const page = getPageById(pageIds.NETWORK, locale);
  const navigation = getMainNav(locale);
  const network = getNetwork();
  const supporters = getSupporters();
  const media = getMedia();

  const data = await Promise.all([
    page,
    navigation,
    network,
    supporters,
    media,
  ]);

  if (!navigation) {
    throw new Response("Could not load navigation", { status: 404 });
  }

  return [...data, locale];
};

export default function SupportMedia() {
  const [page, navigation, network, supporters, media, locale] =
    useLoaderData();
  const { t } = useTranslation("networkPartnerMedia");
  return (
    <BasicLayout nav={navigation.fields.items} lang="de">
      <div className="container mx-auto max-w-6xl">
        <div className="pt-24">
          <section className="mx-auto max-w-7xl py-12 px-4 md:px-12">
            <h2 className="mb-12 font-headline text-4xl font-bold">
              {t("title.network")}
            </h2>
            {network.length && (
              <div
                style={{
                  gridTemplateColumns: "repeat(auto-fit,minmax(270px, 1fr))",
                }}
                className={"grid-rows-auto grid gap-x-4 gap-y-8"}
              >
                {network.map((entry: any) => (
                  <SupporterTile
                    key={entry.fields.url}
                    image={entry.fields.image.fields.file.url}
                    url={entry.fields.url}
                  />
                ))}
              </div>
            )}
          </section>
        </div>

        {supporters && (
          <section className="mx-auto max-w-7xl py-12 px-4 md:px-12">
            <h2 className="mb-12 font-headline text-4xl font-bold">
              {t("title.partner")}
            </h2>
            <div
              style={{
                gridTemplateColumns: "repeat(auto-fit,minmax(270px, 1fr))",
              }}
              className="grid-rows-auto grid gap-x-4 gap-y-8"
            >
              {supporters.map((entry: any) => (
                <SupporterTile
                  key={entry.fields.url}
                  url={entry.fields.url}
                  image={entry.fields.image.fields.file.url}
                />
              ))}
            </div>
          </section>
        )}
      </div>
      <ContentBlocks content={page.fields.content} locale={locale} />
      {media && (
        <section className="mx-auto max-w-7xl py-12 px-4 md:px-12">
          <h2 className="mb-12 font-headline text-4xl font-bold">
            {t("title.media")}
          </h2>
          <div
            style={{
              gridTemplateColumns: "repeat(auto-fit,minmax(270px, 1fr))",
            }}
            className="grid-rows-auto grid gap-x-4 gap-y-8"
          >
            {media.map((entry: any) => (
              <SupporterTile
                key={entry.fields.url}
                url={entry.fields.url}
                image={entry.fields.image.fields.file.url}
                title={entry.fields.title}
              />
            ))}
          </div>
        </section>
      )}
    </BasicLayout>
  );
}
