// app/components/CleverLink.tsx
import { Link } from "@remix-run/react";
import type { RemixLinkProps } from "@remix-run/react/components";
import type { ReactNode } from "react";

interface CleverLinkProps extends RemixLinkProps {
  to: string;
  children: ReactNode;
  className?: string;
}

export default function CleverLink({
  to,
  prefetch = "intent",
  children,
  className,
}: CleverLinkProps) {
  if (!to) {
    throw new Error('"to" prop is required');
  }
  const isInternalLink =
    to.startsWith("https://www.virtualsupporttalks.de/") ||
    to.startsWith("/") ||
    !to.startsWith("https://");
  if (isInternalLink) {
    const usedLink = to.replace("https://www.virtualsupporttalks.de", "");
    return (
      <Link className={className} to={usedLink} prefetch={prefetch}>
        {children}
      </Link>
    );
  }
  return (
    <a
      href={to}
      target="_blank"
      className={className}
      rel="noopener noreferrer"
    >
      {children}
    </a>
  );
}

// components/CleverLink.vue
<template>
  <component :is="linkComponent" v-bind="linkAttrs">
    <slot />
  </component>
</template>

<script>
export default {
  name: 'CleverLink',

  props: {
    to: {
      type: String,
      required: true,
    },
  },

  computed: {
    linkComponent() {
      if (this.isInternalLink) {
        return 'NuxtLink'
      }
      return 'a'
    },

    isInternalLink() {
      return (
        this.to.startsWith('https://www.virtualsupporttalks.de/') ||
        this.to.startsWith('/')
      )
    },

    linkAttrs() {
      let usedLink = this.to
      if (this.isInternalLink) {
        usedLink = this.to.replace('https://www.virtualsupporttalks.de', '')
        return {
          ...this.$attrs,
          to: this.localePath(usedLink),
        }
      }
      return {
        ...this.$attrs,
        href: usedLink,
        rel: 'noopener',
        target: '_blank',
      }
    },
  },
}
</script>
