// app/components/ContentBlocks.tsx
import type {
  IBlogpostFields,
  ICenteredContentFields,
  IContentImageBgFields,
  IContentWithFullSizeImageFields,
  IGenericContentFields,
  IHeaderBlockFields,
  IImageCollectionFields,
  IPageFields,
  ITrackingGaFields,
  ITwoImagesFields,
  IVideoPlayerFields,
  LOCALE_CODE,
} from "../../@types/generated/contentful";
import ContentBlockBlogPreview from "./ContentBlocks/BlogPreview";
import ContentBlockCentered from "./ContentBlocks/Centered";
import ContentBlockImageCollection from "./ContentBlocks/ContentBlockImageCollection";
import ContentBlockFullSizeImageBg from "./ContentBlocks/FullSizeImageBg";
import GenericContent from "./ContentBlocks/GenericContent";
import ContentBlockHeader from "./ContentBlocks/Header";
import ContentBlockImageBg from "./ContentBlocks/ImageBg";
import TrackingGa from "./ContentBlocks/TrackingGA";
import ContentBlockTwoImages from "./ContentBlocks/TwoImages";
import VideoPlayer from "./ContentBlocks/VideoPlayer";
import ContentfulRichText from "./ContentfulRichText";

type ContentBlockProps = {
  content: IPageFields["content"] | IBlogpostFields["content"];
  locale: LOCALE_CODE;
};

export default function ContentBlocks({ content, locale }: ContentBlockProps) {
  return (
    <div>
      {content.map((item, index) => {
        const {
          sys: {
            contentType: {
              sys: { id },
            },
          },
        } = item;

        if (id === "headerBlock") {
          const { backgroundcolor, image, buttonText, buttonUrl } =
            item.fields as IHeaderBlockFields;
          return (
            <ContentBlockHeader
              key={item.sys.id}
              backgroundcolor={backgroundcolor}
              image={image}
              buttonText={buttonText}
              buttonUrl={buttonUrl}
            />
          );
        }

        if (id === "centeredContent") {
          const { bgcolor, content, buttonText, buttonUrl } =
            item.fields as ICenteredContentFields;
          return (
            <ContentBlockCentered
              key={item.sys.id}
              bgcolor={bgcolor}
              content={content}
              buttonText={buttonText}
              buttonUrl={buttonUrl}
            />
          );
        }
        if (id === "contentWithFullSizeImage") {
          const { backgroundcolor, image, imageRight, content } =
            item.fields as IContentWithFullSizeImageFields;
          return (
            <ContentBlockFullSizeImageBg
              key={item.sys.id}
              backgroundcolor={backgroundcolor}
              image={image}
              imageRight={imageRight}
            >
              {content && <ContentfulRichText content={content} />}
            </ContentBlockFullSizeImageBg>
          );
        }
        if (id === "contentImageBg") {
          const {
            backgroundImage,
            buttonUrl,
            buttonText,
            withCharityBanner,
            content,
          } = item.fields as IContentImageBgFields;
          return (
            <ContentBlockImageBg
              key={item.sys.id}
              backgroundImage={backgroundImage}
              buttonUrl={buttonUrl}
              buttonText={buttonText}
              withCharityBanner={withCharityBanner}
              withPaddingTop={index === 0}
            >
              {content && <ContentfulRichText content={content} />}
            </ContentBlockImageBg>
          );
        }
        if (id === "twoImages") {
          const { image1, image2, text1, text2, link1, link2 } =
            item.fields as ITwoImagesFields;
          return (
            <ContentBlockTwoImages
              key={item.sys.id}
              image1={image1}
              image2={image2}
              text1={text1}
              text2={text2}
              link1={link1}
              link2={link2}
              locale={locale}
            />
          );
        }

        if (id === "videoPlayer") {
          const { videoId, content, showOnlyOnGermanPage } =
            item.fields as IVideoPlayerFields;
          if (
            !showOnlyOnGermanPage ||
            (locale === "de" && showOnlyOnGermanPage)
          ) {
            return (
              <VideoPlayer
                key={item.sys.id}
                videoId={videoId}
                content={content}
              />
            );
          }
        }

        if (id === "imageCollection") {
          const { internalTitle, images } =
            item.fields as IImageCollectionFields;
          return (
            <ContentBlockImageCollection
              key={item.sys.id}
              images={images}
              internalTitle={internalTitle}
              withPaddingTop={index === 0}
            />
          );
        }

        if (id === "BlogPreview") {
          const { titleAndHeader, buttonText } = item.fields as any;

          return (
            <ContentBlockBlogPreview
              key={item.sys.id}
              titleAndHeader={titleAndHeader}
              buttonText={buttonText}
            ></ContentBlockBlogPreview>
          );
        }

        if (id === "trackingGa") {
          const { title } = item.fields as ITrackingGaFields;
          return <TrackingGa key={item.sys.id} title={title} />;
        }

        if (id === "coachList") {
          return null;
        } else {
          const { content } = item.fields as IGenericContentFields;

          return <GenericContent key={item.sys.id} content={content} />;
        }
      })}
    </div>
  );
}

// components/ContentBlocks.vue
<template>
  <div>
    <template v-for="(block, index) in blocks">
      <HeaderBlock
        v-if="block.sys.contentType.sys.id === 'headerBlock'"
        :key="block.sys.id"
        v-bind="block.fields"
      />
      <ContentCentered
        v-else-if="block.sys.contentType.sys.id === 'centeredContent'"
        :key="block.sys.id"
        :backgroundcolor="block.fields.backgroundcolor"
        :textcolor="block.fields.textcolor"
        :button-url="block.fields.buttonUrl"
        :button-text="block.fields.buttonText"
        :bgcolor="block.fields.bgcolor"
        :content="block.fields.content"
      />
      <ContentImageBg
        v-else-if="block.sys.contentType.sys.id === 'contentImageBg'"
        :key="block.sys.id"
        :with-padding-top="index === 0"
        v-bind="block.fields"
      >
        <ContentfulRichText :content="block.fields.content" />
      </ContentImageBg>
      <ContentWithFullSizeImage
        v-else-if="block.sys.contentType.sys.id === 'contentWithFullSizeImage'"
        :key="block.sys.id"
        :background-color="block.fields.backgroundcolor"
        :image="block.fields.image.fields.file.url"
        :image-right="block.fields.imageRight"
      >
        <ContentfulRichText :content="block.fields.content" />
      </ContentWithFullSizeImage>
      <TwoImages
        v-else-if="block.sys.contentType.sys.id === 'twoImages'"
        :key="block.sys.id"
        :image1="block.fields.image1.fields.file.url"
        :image2="block.fields.image2.fields.file.url"
        :text1="block.fields.text1"
        :text2="block.fields.text2"
        :link1="block.fields.link1"
        :link2="block.fields.link2"
      />
      <ContentBlockImageCollection
        v-else-if="block.sys.contentType.sys.id === 'imageCollection'"
        :key="block.sys.id"
        :images="block.fields.images"
        :with-padding-top="index === 0"
      />
      <ContentBlockCoachList
        v-else-if="block.sys.contentType.sys.id === 'coachList'"
        :key="block.sys.id"
      />
      <GenericContent v-else :key="block.sys.id" :block="block" />
    </template>
  </div>
</template>
<script>
export default {
  props: {
    blocks: {
      type: Array,
      required: true,
    },
  },
}
</script>
