// app/components/ContentBlocks/ContentBlockImageCollection.tsx
import type { IImageCollectionFields } from "../../../@types/generated/contentful";

interface ImageCollectionProps extends IImageCollectionFields {
  withPaddingTop: boolean;
}

function Image({ image, text }: { image?: string; text?: string }) {
  return (
    <picture>
      <source
        srcSet={`
    ${image}?h=450&fm=webp,
    ${image}?h=900&fm=webp 2x`}
        type="image/webp"
      />
      <source
        srcSet={`
  ${image}?h=450&fm=jpeg,
  ${image}?h=900&fm=jpeg 2x`}
        type="image/jpeg"
      />
      <img
        src={`${image}?h=450`}
        alt={text}
        height="450"
        loading="lazy"
        className="h-auto max-w-full"
      />
    </picture>
  );
}

export default function ContentBlockImageCollection({
  images,
  withPaddingTop,
}: ImageCollectionProps) {
  const imageCollection = images?.map(({ sys, fields }) => ({
    image: fields?.image?.fields.file.url,
    link: fields.url,
    text: fields.internalTitle,
    id: sys.id,
  }));

  return (
    <div
      className={`mx-auto grid max-w-7xl grid-cols-1 gap-4 p-4 md:grid-cols-2 md:gap-8 lg:grid-cols-3 lg:gap-12${
        withPaddingTop && "pt-20"
      }`}
    >
      {imageCollection?.map(({ image, link, text, id }) => (
        <figure key={id} role="figure" aria-label="text">
          {link ? (
            <a href={link}>
              <Image image={image} text={text} />
            </a>
          ) : (
            <div>
              <Image image={image} text={text} />
            </div>
          )}
        </figure>
      ))}
    </div>
  );
}

// components/ContentBlockImageCollection.vue
<template>
  <div
    :class="[
      'p-4 max-w-7xl mx-auto grid gap-4 grid-cols-1 md:grid-cols-2 md:gap-8 lg:grid-cols-3 lg:gap-12',
      withPaddingTop && 'pt-20',
    ]"
  >
    <figure
      v-for="{ sys, fields } in images"
      :key="sys.id"
      role="figure"
      :aria-label="fields.image.fields.title"
    >
      <component :is="getComponent(fields)" v-bind="getFieldData(fields)">
        <picture>
          <source
            :srcset="`
              ${fields.image.fields.file.url}?h=450&fm=webp,
              ${fields.image.fields.file.url}?h=900&fm=webp 2x`"
            type="image/webp"
          />
          <source
            :srcset="`
              ${fields.image.fields.file.url}?h=450&fm=jpeg,
              ${fields.image.fields.file.url}?h=900&fm=jpeg 2x`"
            type="image/jpeg"
          />
          <img
            :src="`${fields.image.fields.file.url}?h=450`"
            :alt="fields.image.fields.title"
            height="450"
            loading="lazy"
            class="max-w-full h-auto"
          />
        </picture>
      </component>
    </figure>
  </div>
</template>

<script>
export default {
  name: 'ContentBlockImageCollection',

  props: {
    images: {
      type: Array,
      default: () => [],
    },
    withPaddingTop: {
      type: Boolean,
      default: false,
    },
  },

  methods: {
    getComponent(fields) {
      if (fields.url) {
        return 'a'
      }
      return 'div'
    },

    getFieldData(fields) {
      if (fields.url) {
        return {
          href: fields.url,
          target: '_blank',
        }
      }
      return {}
    },
  },
}
</script>
