// app/components/ContentfulRichText.tsx
import type { Options } from "@contentful/rich-text-react-renderer";
import { documentToReactComponents } from "@contentful/rich-text-react-renderer";
import type { Document } from "@contentful/rich-text-types";
import { INLINES } from "@contentful/rich-text-types";
import type { ReactNode } from "react";
import CleverLink from "./CleverLink";

type ContentfulRichTextProps = {
  content: Document;
  withProse?: boolean;
  useWhiteProse?: boolean;
};

export default function ContentfulRichText({
  content,
  withProse = true,
  useWhiteProse = false,
}: ContentfulRichTextProps) {
  const options: Options = {
    renderNode: {
      [INLINES.HYPERLINK]: (node, children: ReactNode) => (
        <CleverLink to={node.data.uri} prefetch="intent">
          {node.data.url} {children}
        </CleverLink>
      ),
    },
  };
  return (
    <div
      className={`richtext prose-a:text-vsp-600 hover:prose-a:text-vsp-700 lg:prose-h1:leading-[1.15] ${
        withProse && "prose prose-slate max-w-none lg:prose-lg prose-headings:font-headline"
      } ${useWhiteProse && "prose-white prose-a:text-vsp-300 hover:prose-a:text-vsp-100"}`}
    >
      {content && documentToReactComponents(content, options)}
    </div>
  );
}

// components/ContentfulRichText.vue
<template>
  <div
    :class="[
      'richtext prose-a:text-vsp-600 hover:prose-a:text-vsp-700',
      withProse && 'prose lg:prose-lg max-w-none prose-headings:font-headline',
      useWhiteProse &&
        'prose-white prose-a:text-vsp-300 hover:prose-a:text-vsp-100',
    ]"
  >
    <RichTextRenderer
      v-if="!!content"
      :document="content"
      :node-renderers="renderNodes"
    />
  </div>
</template>

<script>
import { INLINES } from '@contentful/rich-text-types'
import RichTextRenderer from 'contentful-rich-text-vue-renderer'
import CleverLink from '~/components/CleverLink.vue'

export default {
  name: 'ContentfulRichText',
  components: {
    RichTextRenderer,
  },
  props: {
    content: {
      type: Object,
      required: true,
    },
    withProse: {
      type: Boolean,
      default: true,
    },
    useWhiteProse: {
      type: Boolean,
      default: false,
    },
  },
  computed: {
    renderNodes() {
      return {
        [INLINES.HYPERLINK]: (node, key, h, next) => {
          return h(
            CleverLink,
            {
              key,
              props: {
                to: node.data.uri,
              },
            },
            next(node.content, key, h, next)
          )
        },
      }
    },
  },
}
</script>

<style scoped>
.richtext >>> li > p {
  margin: 0;
}
</style>
