// app/components/SupporterTile.tsx
export default function SupporterTile({
	url,
	image,
	title,
}: {
	url: string;
	image?: string;
	title?: string;
}) {
	return (
		<a
			href={url}
			className="flex items-center justify-center no-underline transition-opacity hover:opacity-80 focus:opacity-80 active:opacity-80"
		>
			<div className="text-center">
				<picture>
					<source srcSet={`${image}?w=240&h=240&fit=pad&fm=webp`} type="image/webp" />
					<source srcSet={`${image}?w=240&h=240&fit=pad&fm=jpeg`} type="image/jpeg" />
					<img
						src={`${image}?w=240&h=240&fit=pad`}
						alt={title}
						loading="lazy"
						className="m-auto max-h-[300px] w-[80%] max-w-[300px] object-cover"
					/>
				</picture>
				{title && <h3 className="m-0 text-lg font-bold">{title}</h3>}
			</div>
		</a>
	);
}

// components/SupporterTile.vue
<template>
  <a
    :href="url"
    class="supporter"
    target="_blank"
    rel="noreferrer noopener"
    loading="lazy"
  >
    <div>
      <picture>
        <source
          :srcset="`${image}?w=240&h=240&fit=pad&fm=webp`"
          type="image/webp"
        />
        <source
          :srcset="`${image}?w=240&h=240&fit=pad&fm=jpeg`"
          type="image/webp"
        />
        <img
          :src="`${image}?w=240&h=240&fit=pad`"
          :alt="title"
          loading="lazy"
        />
      </picture>
      <h3 v-if="title">{{ title }}</h3>
    </div>
  </a>
</template>

<script>
export default {
  name: 'SupporterTile',

  props: {
    url: {
      type: String,
      default: null,
    },
    image: {
      type: String,
      default: null,
    },
    title: {
      type: String,
      default: null,
    },
  },
}
</script>

<style scoped>
.supporter {
  display: flex;
  align-items: center;
  justify-content: center;
  transition: opacity 300ms ease-in;
  text-decoration: none;
  content-visibility: auto;
  contain-intrinsic-size: 350px;
}

.supporter:hover,
.supporter:focus,
.supporter:active {
  opacity: 0.8;
}
.supporter div {
  text-align: center;
}

.supporter h3 {
  margin: 0;
}

.supporter img {
  object-fit: cover;
  max-width: 300px;
  max-height: 300px;
  width: 80%;
  margin: auto;
}
</style>
